import { ResolvedConfig, EgressRule } from './types';

/**
 * Escape a string for safe interpolation into a JavaScript string literal.
 * Prevents injection of arbitrary JS via crafted host/path values.
 */
function escapeJsString(s: string): string {
    return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\r/g, '\\r').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
}

/**
 * Generate a single httpjail JavaScript rule expression for a rule.
 * httpjail rules are JS expressions that return true (allow) or false (block).
 * Available variables in httpjail rule context: host, method, path, url
 */
function ruleToExpression(rule: EgressRule): string {
    const conditions: string[] = [];

    // Host matching: support wildcards like *.github.com
    if (rule.host.startsWith('*.')) {
        const domain = escapeJsString(rule.host.slice(2));
        conditions.push(`(host === "${domain}" || host.endsWith(".${domain}"))`);
    } else {
        conditions.push(`host === "${escapeJsString(rule.host)}"`);
    }

    // Method filtering
    if (rule.methods && rule.methods.length > 0) {
        const methodList = rule.methods.map(m => `"${escapeJsString(m)}"`).join(', ');
        conditions.push(`[${methodList}].includes(method)`);
    }

    // Path filtering
    if (rule.paths && rule.paths.length > 0) {
        const pathChecks = rule.paths.map(p => `path.startsWith("${escapeJsString(p)}")`).join(' || ');
        conditions.push(`(${pathChecks})`);
    }

    return conditions.join(' && ');
}

/**
 * Generate httpjail rules JavaScript file content from a rules array.
 * Returns true to allow, false to block.
 */
export function generateHttpjailRulesFromArray(rules: EgressRule[]): string {
    const lines: string[] = [
        '// Auto-generated by Egressor - do not edit manually',
        '// httpjail rule file: returns true to allow a request, false to block',
        '',
    ];

    if (rules.length === 0) {
        lines.push('// No rules configured - block all traffic');
        lines.push('false');
        return lines.join('\n');
    }

    const expressions = rules.map((rule, i) => {
        const safeDesc = rule.description ? rule.description.replace(/[\r\n\u2028\u2029]/g, ' ') : '';
        const comment = safeDesc ? ` // ${safeDesc}` : '';
        const expr = ruleToExpression(rule);
        if (i === 0) {
            return `(${expr})${comment}`;
        }
        return `|| (${expr})${comment}`;
    });

    lines.push('// Allow requests matching any of these rules:');
    lines.push(...expressions);

    return lines.join('\n');
}

/**
 * Generate the full httpjail rules JavaScript file content.
 * The file exports a single function that httpjail calls for each request.
 * Returns true to allow, false to block.
 */
export function generateHttpjailRules(config: ResolvedConfig): string {
    return generateHttpjailRulesFromArray(config.rules);
}

/**
 * Generate per-container httpjail rule files.
 * Returns a Map of container config name -> rules file content.
 */
export function generatePerContainerHttpjailRules(config: ResolvedConfig): Map<string, string> {
    const result = new Map<string, string>();
    for (const container of config.containers) {
        result.set(container.name, generateHttpjailRulesFromArray(container.rules));
    }
    return result;
}

/**
 * Generate a compact, single-expression version of the rules.
 * Useful for passing as a command-line argument.
 */
export function generateHttpjailRuleExpression(config: ResolvedConfig): string {
    if (config.rules.length === 0) {
        return 'false';
    }

    const expressions = config.rules.map(rule => `(${ruleToExpression(rule)})`);
    return expressions.join(' || ');
}
